pipeline {
    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -la'
            }
        }

        stage('Build and Test') {
            steps {
                sh '''
                    cd spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        cd spring-boot-app

                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                          -Dsonar.projectKey=my-ec2-project \
                          -Dsonar.projectName="Spring Boot App" \
                          -Dsonar.host.url="${SONAR_HOST_URL}"
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "arjunsurya27/spring-boot-app:${BUILD_NUMBER}"
            }

            steps {
                script {
                    sh '''
                        cd spring-boot-app
                        docker build -t ${DOCKER_IMAGE} .
                    '''

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'docker-cred'
                    ) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_USER_NAME = "arjunsurya9955"
            }

            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-id',
                        usernameVariable: 'GITHUB_USERNAME',
                        passwordVariable: 'GITHUB_TOKEN'
                    )
                ]) {
                    sh '''
                        echo "Current directory:"
                        pwd
                        git config --global --add safe.directory "${WORKSPACE}"

                        echo "Git status:"
                        git status

                        git config --global user.email "arjunsurya027@gmail.com"
                        git config --global user.name "${GIT_USER_NAME}"

                        echo "Updating deployment image..."

                        sed -i "s|image: .*|image: arjunsurya27/spring-boot-app:${BUILD_NUMBER}|g" \
                        spring-boot-app-manifests/deployment.yml

                        echo "Deployment file after update:"
                        cat spring-boot-app-manifests/deployment.yml

                        git add spring-boot-app-manifests/deployment.yml

                        git commit -m "Update spring-boot image tag to ${BUILD_NUMBER} [skip ci]" \
                        || echo "No changes to commit"

                        git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/java-maven-sonar-argocd.git HEAD:main
                    '''
                }
            }
        }
    }
}
