pipeline {

    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo passed'

                // If Jenkins is not already checking out the repository,
                // uncomment the following line:
                // git branch: 'main', url: 'https://github.com/arjunsurya9955/java-maven-sonar-argocd.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh 'ls -ltr'

                sh '''
                    cd spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {

                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('sonarqube') {

                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=my-ec2-project \
                            -Dsonar.sources=spring-boot-app/src
                        """
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {

            environment {
                DOCKER_IMAGE = "arjunsurya27/spring-boot-app:${BUILD_NUMBER}"
            }

            steps {
                script {

                    sh '''
                        cd spring-boot-app
                        docker build -t ${DOCKER_IMAGE} .
                    '''

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'docker-cred'
                    ) {

                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Update Deployment File') {

            environment {
                GIT_REPO_NAME = "java-maven-sonar-argocd"
                GIT_USER_NAME = "arjunsurya9955"
            }

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'github',
                        usernameVariable: 'GITHUB_USERNAME',
                        passwordVariable: 'GITHUB_TOKEN'
                    )
                ]) {

                    sh '''
                        git config user.email "arjunsurya027@gmail.com"
                        git config user.name "${GIT_USER_NAME}"

                        sed -i "s|image: .*|image: arjunsurya27/spring-boot-app:${BUILD_NUMBER}|g" spring-boot-app-manifests/deployment.yml

                        git add spring-boot-app-manifests/deployment.yml

                        git commit -m "Update Spring Boot image tag to ${BUILD_NUMBER} [skip ci]" || echo "No changes to commit"

                        git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                    '''
                }
            }
        }
    }
}
